export const SAVE_USER = 'SAVE_USER';
export const SAVE_SESSION = 'SAVE_SESSION';
export const REMOVE_DATA = 'REMOVE_DATA';

export const FETCH_FORM_CATEGORIES = 'FETCH_FORM_CATEGORIES';
export const FETCH_FORM_CATEGORIES_SUCCESS = 'FETCH_FORM_CATEGORIES_SUCCESS';
export const FETCH_FORM_CATEGORIES_ERROR = 'FETCH_FORM_CATEGORIES_ERROR';
