export const SAVE_USER = 'SAVE_USER';
export const SAVE_SESSION = 'SAVE_SESSION';
export const REMOVE_DATA = 'REMOVE_DATA';

export const FETCH_FORM_CATEGORIES = 'FETCH_FORM_CATEGORIES';
export const FETCH_FORM_CATEGORIES_SUCCESS = 'FETCH_FORM_CATEGORIES_SUCCESS';
export const FETCH_FORM_CATEGORIES_ERROR = 'FETCH_FORM_CATEGORIES_ERROR';

export const CREATE_FORM = 'CREATE_FORM';
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS';
export const CREATE_FORM_ERROR = 'CREATE_FORM_ERROR';

export const FETCH_FORMS = 'FETCH_FORMS';
export const FETCH_FORMS_SUCCESS = 'FETCH_FORMS_SUCCESS';
export const FETCH_FORMS_ERROR = 'FETCH_FORMS_ERROR';
