version: 2
jobs:
  build:
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn cache
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - run:
          name: Run server
          command: yarn start
          background: true
      - run:
          name: Run tests
          command: yarn test:ci
      - run:
          name: Run Jest tests
          command: yarn jest src
      - run:
          name: Run linter
          command: yarn lint
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Setup Code Climate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build -t lcov ./coverage/lcov.info
